-- MySQL Script generated by MySQL Workbench
-- Tue Jun 22 16:46:53 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CycloNext
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CycloNext
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CycloNext` DEFAULT CHARACTER SET utf8 ;
USE `CycloNext` ;

-- -----------------------------------------------------
-- Table `CycloNext`.`tb_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CycloNext`.`tb_usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CycloNext`.`tb_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CycloNext`.`tb_grupo` (
  `id_grupo` INT NOT NULL AUTO_INCREMENT,
  `nome_grupo` VARCHAR(100) NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `fk_usuario_admin` INT NOT NULL,
  PRIMARY KEY (`id_grupo`, `fk_usuario_admin`),
  INDEX `fk_Grupo_Usuário1_idx` (`fk_usuario_admin` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_Usuário1`
    FOREIGN KEY (`fk_usuario_admin`)
    REFERENCES `CycloNext`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CycloNext`.`tb_postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CycloNext`.`tb_postagem` (
  `id_postagem` INT NOT NULL AUTO_INCREMENT,
  `corpo` TEXT(500) NOT NULL,
  `imagem/video` VARCHAR(255) NULL,
  `tipo_postagem` ENUM('doacao', 'texto', 'agradecimento') NOT NULL,
  `data` DATETIME NOT NULL,
  `fk_usuario_admin` INT NULL,
  `fk_id_grupo` INT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_postagem`),
  INDEX `fk_Postagem_Grupo1_idx` (`fk_id_grupo` ASC, `fk_usuario_admin` ASC) VISIBLE,
  INDEX `fk_Postagem_Usuário1_idx` (`fk_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Postagem_Grupo1`
    FOREIGN KEY (`fk_id_grupo` , `fk_usuario_admin`)
    REFERENCES `CycloNext`.`tb_grupo` (`id_grupo` , `fk_usuario_admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Postagem_Usuário1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `CycloNext`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CycloNext`.`tb_membro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CycloNext`.`tb_membro` (
  `fk_id_grupo` INT NOT NULL,
  `fk_id_usuario` INT NOT NULL,
  PRIMARY KEY (`fk_id_grupo`, `fk_id_usuario`),
  INDEX `fk_Grupo_has_Usuário_Usuário1_idx` (`fk_id_usuario` ASC) VISIBLE,
  INDEX `fk_Grupo_has_Usuário_Grupo_idx` (`fk_id_grupo` ASC) VISIBLE,
  CONSTRAINT `fk_Grupo_has_Usuário_Grupo`
    FOREIGN KEY (`fk_id_grupo`)
    REFERENCES `CycloNext`.`tb_grupo` (`id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_has_Usuário_Usuário1`
    FOREIGN KEY (`fk_id_usuario`)
    REFERENCES `CycloNext`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CycloNext`.`tb_seguidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CycloNext`.`tb_seguidor` (
  `fk_follows` INT NOT NULL,
  `fk_followed` INT NOT NULL,
  PRIMARY KEY (`fk_follows`, `fk_followed`),
  INDEX `fk_tb_usuario_has_tb_usuario_tb_usuario2_idx` (`fk_followed` ASC) VISIBLE,
  INDEX `fk_tb_usuario_has_tb_usuario_tb_usuario1_idx` (`fk_follows` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuario_has_tb_usuario_tb_usuario1`
    FOREIGN KEY (`fk_follows`)
    REFERENCES `CycloNext`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_usuario_has_tb_usuario_tb_usuario2`
    FOREIGN KEY (`fk_followed`)
    REFERENCES `CycloNext`.`tb_usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
